---
- name: Add repository
  ansible.builtin.apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ {{ ansible_facts['lsb']['codename'] }} nginx
    state: present
    filename: nginx
  register: repo
  ignore_errors: true

- name: Add dirmngr package
  ansible.builtin.apt:
    name: dirmngr
    state: present
  when: repo.failed

- name: Adding repository key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ repo | regex_search('^.* NO_PUBKEY (\\w*)', '\\1') | first }}"
  when: repo.failed

- name: Re-adding repository
  ansible.builtin.apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ {{ ansible_facts['lsb']['codename'] }} nginx
    state: present
    filename: nginx
  when: repo.failed

- name: Installing Nginx package
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  notify:
    - Enable and start Nginx

- name: Remove default virtualhost
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
