---
- name: Check if git package is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Download source code of modules from git repositories
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "/tmp/{{ item.split('/')[-1].split('.')[0] }}"
    version: master
  with_items: "{{ nginx_add_modules }}"
  register: git_repos
