---
- name: Check if git package is installed
  package:
    name: git
    state: present

- name: Download source code of modules from git repositories
  git:
    repo: "{{ item }}"
    dest: "/tmp/{{ item.split('/')[-1].split('.')[0] }}"
  with_items: "{{ nginx_add_modules }}"
  register: git_repos
