---
- name: Install Nginx
  include_tasks: install.yml
  when: install_from == "repo"

- name: Build from source
  include_tasks: build.yml
  when: install_from == "source"

- name: Create Nginx configure file
  include_tasks: config.yml

- name: Setup Virtual servers
  include_tasks: virtual_servers.yml
  when: nginx_virtual_servers is defined

- name: Setup TCP and UDP Load Balancing
  include_tasks: tcp_udp_nlb.yml
  when: tcp_udp_nlb is defined

- name: Delete unmanaged configuration files
  include_tasks: unmanaged.yml

- name: Using the stub_status Module
  import_tasks: stub_status.yml
  when: stub_status
