---
- name: Install the EPEL repository
  yum:
    name: epel-release
    state: present
    update_cache: true

- name: Install Nginx
  yum:
    name:
      - nginx
      - policycoreutils-python-utils
    state: present
  notify:
    - Enable and start Nginx

- name: Remove default virtualhost
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: ansible_facts.selinux.status == 'enabled'
