---
- name: Create stub_status config
  ansible.builtin.template:
    src: stub_status.conf.j2
    dest: /etc/nginx/conf.d/stub_status.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload Nginx configuration
