---
stub_status: true
nginx_virtual_servers:
  - listen: 8080
    locations:
      - location: /
        params:
          - proxy_pass https://google.com;
  - listen: 9080
    locations:
      - location: /
        params:
          - proxy_pass https://google.com;
copy_ssl_certs: True
tcp_udp_nlb:
  - name: example1
    listen: 
      - 8443 ssl
    proxy_ssl: on
    ssl_certificate: "{{ ssl_cert_path }}/localhost1.crt"
    ssl_certificate_key: "{{ ssl_cert_path }}/localhost1.key"
    servers:
      - google.com:443
  - name: example2
    listen: 
      - 9443
    servers:
      - google.com:443