---
install_from: source
nginx_with_modules:
  - --with-file-aio 
  - --with-ipv6 
  - --with-http_ssl_module
  - --with-http_v2_module 
  - --with-http_realip_module 
  - --with-http_addition_module 
  - --with-http_xslt_module=dynamic  
  - --with-http_image_filter_module=dynamic
  - --with-http_sub_module 
  - --with-http_dav_module 
  - --with-http_flv_module 
  - --with-http_mp4_module 
  - --with-http_gunzip_module 
  - --with-http_gzip_static_module 
  - --with-http_random_index_module 
  - --with-http_secure_link_module 
  - --with-http_degradation_module 
  - --with-http_slice_module 
  - --with-http_stub_status_module 
  - --with-http_perl_module=dynamic 
  - --with-http_auth_request_module 
  - --with-mail=dynamic 
  - --with-mail_ssl_module  
  - --with-stream=dynamic
  - --with-stream_ssl_module 
  - --with-debug
stub_status: true
nginx_virtual_servers:
  - listen: 8080
    locations:
      - location: /
        params:
          - proxy_pass https://google.com;
  - listen: 9080
    locations:
      - location: /
        params:
          - proxy_pass https://google.com;
tcp_udp_nlb:
  - name: example1
    listen: 
      - 8443
    servers:
      - google.com:443
  - name: example2
    listen: 
      - 9443
    servers:
      - google.com:443