---
- name: Enable and start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
    daemon_reload: true

- name: Reload Nginx configuration
  ansible.builtin.service:
    name: nginx
    state: reloaded
