---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_8
    image: docker.io/pycontribs/centos:8
    command: /sbin/init
    privileged: True
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
